# Generated by Django 6.0.3 on 2026-04-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
