# Generated by Django 6.0.3 on 2026-06-16 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_inscripcion_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción o Instrucciones')),
                ('fecha_limite', models.DateTimeField(verbose_name='Fecha y Hora Límite')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas/', verbose_name='Archivo Adjunto')),
                ('texto_respuesta', models.TextField(blank=True, null=True, verbose_name='Respuesta de Texto')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Calificar'), ('calificado', 'Calificado')], default='pendiente', max_length=15)),
                ('nota', models.FloatField(blank=True, null=True, verbose_name='Nota Obtenida')),
                ('retroalimentacion', models.TextField(blank=True, null=True, verbose_name='Comentarios del Docente')),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='cursos.actividad')),
                ('estudiante', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
    ]
