# Generated by Django 6.0.3 on 2026-06-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_materia_curso_docentes_alter_curso_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='actividades/', verbose_name='Archivo Adjunto (Opcional)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='limite_estudiantes',
            field=models.PositiveIntegerField(default=30, verbose_name='Límite de Estudiantes'),
        ),
    ]
