# Generated by Django 6.0.3 on 2026-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_actividad_archivo_curso_limite_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='cursos/materiales/', verbose_name='Archivo del Curso (Opcional)'),
        ),
    ]
